wpilibsuite/SmartDashboard

smartdashboard/build.gradle

This changes the version to be based on annotated git tags, and updates ntcore use the most recently published version.

Updates the gradle build to use the WPILibVersioning plugin

---

smartdashboard/src/edu/wpi/first/smartdashboard/gui/Widget.java

Allow any number of decimal places

---

smartdashboard/src/edu/wpi/first/smartdashboard/gui/DashboardPrefs.java
smartdashboard/src/edu/wpi/first/smartdashboard/main.java
smartdashboard/src/edu/wpi/first/smartdashboard/robot/Robot.java

Combined with https://github.com/wpilibsuite/ntcore/pull/151, this results in much better connection robustness.

Use NetworkTable setTeam and setIPAddress.

---

smartdashboard/src/edu/wpi/first/smartdashboard/gui/elements/DefaultDisplayElementRegistrar.java
smartdashboard/src/edu/wpi/first/smartdashboard/gui/elements/MJPGStreamerViewerExtension.java

This is a straight copy and paste from https://github.com/Beachbot330/MJPGStream_SDExtension

Copy MJPG Extension

---

smartdashboard/src/edu/wpi/first/smartdashboard/gui/Widget.java

closes #22 
This will change for all text fields (not just number fields).

First character of text field always visible

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MJPGStreamerViewerExtension.java

Mjpeg host port

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MjpgStreamerViewerExtension.java

Add bandwidth (Mbps) under FPS display.

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MjpgStreamerViewerExtension.java

Handle InterruptedException

---

build.gradle

Fixed the jar base name for jenkins archiving.

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MjpgStreamerViewerExtension.java

Camera Viewer Background Thread Interrupt

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/CameraServerViewer.java
src/main/java/edu/wpi/first/smartdashboard/properties/MultiProperty.java
src/main/java/edu/wpi/first/smartdashboard/properties/Property.java

~This will break CameraServer viewer saving.~

Fix the issues caused by changing MultiProperty

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/LinePlot.java

Add a clear graph property to LinePlot

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/LinePlot.java

Graph X axis based on time rather then updates.

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MjpgStreamViewer.java

closes https://github.com/wpilibsuite/cscore/issues/51

Up readtimeout to 5s

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/Chooser.java

closes #70 
closes #71 
WIP.
This should fix the radio buttons.  Still need to check if the Combo box is going to be an issue.

Fix chooser not showing up if selection is null

---

README.md

Fixes https://www.chiefdelphi.com/forums/showthread.php?threadid=158637

Add section on how to build a runnable jar.

---

README.md

Add download link and fix naming

---

build.gradle
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardFrame.java
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardPanel.java
src/main/java/edu/wpi/first/smartdashboard/gui/GlassPane.java
src/main/java/edu/wpi/first/smartdashboard/gui/elements/Chooser.java
src/main/java/edu/wpi/first/smartdashboard/gui/elements/Scheduler.java
src/main/java/edu/wpi/first/smartdashboard/livewindow/elements/LWSubsystem.java
src/main/java/edu/wpi/first/smartdashboard/types/DataType.java

This PR should be merged before merging:
https://github.com/wpilibsuite/ntcore/pull/213
https://github.com/wpilibsuite/ntcore/pull/214
Looking at this, is it better to do this or to lock the NetworkTables version where it is (Always use version 3.1.7)?

Remove deprecated method usage

---

build.gradle
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardFrame.java
src/main/java/edu/wpi/first/smartdashboard/gui/elements/RobotPreferences.java

This fixes breakages due to the JNI move.
Depends on: wpilibsuite/ntcore#204
Incorporates/supersedes #92

Update to new NetworkTables API.

---

build.gradle

Also update to wpilib-version-plugin 2.0.

Depend on wpiutil 3.+ and ntcore 4.+ rather than just +.

---

fakeRobot/src/main/java/edu/wpi/livewindowfakerobot/LiveWindowFakeRobot.java
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardFrame.java
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardMenu.java
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardPanel.java
src/main/java/edu/wpi/first/smartdashboard/livewindow/elements/LWSubsystem.java
src/main/java/edu/wpi/first/smartdashboard/types/DataType.java

See https://github.com/wpilibsuite/allwpilib/pull/600

Use dotfile format for metadata

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/Subsystem.java

See https://github.com/wpilibsuite/allwpilib/pull/863

Use subsystem command metadata keys

---

src/main/java/edu/wpi/first/smartdashboard/SmartDashboard.java
src/main/java/edu/wpi/first/smartdashboard/extensions/FileSniffer.java
src/main/java/edu/wpi/first/smartdashboard/extensions/FileSnifferClassLoader.java
src/main/java/edu/wpi/first/smartdashboard/xml/XMLWidget.java

Fixes issue #107
I have tested this with a few simple widgets and it seems to be working, but more testing would be good

fix extension loading (fixes issue #107)

---

src/main/java/edu/wpi/first/smartdashboard/SmartDashboard.java
src/main/java/edu/wpi/first/smartdashboard/gui/DashboardPrefs.java
src/main/java/edu/wpi/first/smartdashboard/robot/Robot.java

This makes it easier to connect to simulation, and acts the same as
shuffleboard, OutlineViewer, and the Driver Station

Allow host name or IP address for team number

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/LinePlot.java

This also prevents the graph min/max y-values going above/below each other (and causing an exception).

Adds configurable graph min/max y-values

---

dependencies.gradle

Pin WPILib to 2021.3.1 to avoid build breakage

---

src/main/java/edu/wpi/first/smartdashboard/gui/elements/MjpgStreamViewer.java

This prevents SmartDashboard from inducing 100% CPU when a camera is not available.

Don't busy-wait when a camera is unavailable.

---

.github/workflows/main.yml

Update checkout, setup-java, download and upload artifact

---

fakeRobot/src/main/java/edu/wpi/livewindowfakerobot/LiveWindowFakeRobot.java

Was crashing on start-up because ntcore wasn't loaded
Strip trailing whitespace

Fix FakeRobot by fixing initialization order

---

fakeRobot/src/main/java/edu/wpi/livewindowfakerobot/LiveWindowFakeRobot.java

Update FakeRobot PIDSubsystem to match wpilib

---

.github/workflows/bump.yml

Add action to tag on allwpilib tag dispatch

---

build.gradle

I can't find any documentation for what that option did (if anything), but none of their examples or documentation uses it

Fix publishing to artifactory
